// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: pinchain/pin/query.proto

package pin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName      = "/pinchain.pin.Query/Params"
	Query_PIN_FullMethodName         = "/pinchain.pin.Query/PIN"
	Query_PINsByOwner_FullMethodName = "/pinchain.pin.Query/PINsByOwner"
	Query_PINs_FullMethodName        = "/pinchain.pin.Query/PINs"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// PIN resolves a PIN to its on-chain record.
	PIN(ctx context.Context, in *QueryPINRequest, opts ...grpc.CallOption) (*QueryPINResponse, error)
	// PINsByOwner lists the PINs owned by an address.
	PINsByOwner(ctx context.Context, in *QueryPINsByOwnerRequest, opts ...grpc.CallOption) (*QueryPINsByOwnerResponse, error)
	// PINs lists all registered PINs.
	PINs(ctx context.Context, in *QueryPINsRequest, opts ...grpc.CallOption) (*QueryPINsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PIN(ctx context.Context, in *QueryPINRequest, opts ...grpc.CallOption) (*QueryPINResponse, error) {
	out := new(QueryPINResponse)
	err := c.cc.Invoke(ctx, Query_PIN_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PINsByOwner(ctx context.Context, in *QueryPINsByOwnerRequest, opts ...grpc.CallOption) (*QueryPINsByOwnerResponse, error) {
	out := new(QueryPINsByOwnerResponse)
	err := c.cc.Invoke(ctx, Query_PINsByOwner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PINs(ctx context.Context, in *QueryPINsRequest, opts ...grpc.CallOption) (*QueryPINsResponse, error) {
	out := new(QueryPINsResponse)
	err := c.cc.Invoke(ctx, Query_PINs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// PIN resolves a PIN to its on-chain record.
	PIN(context.Context, *QueryPINRequest) (*QueryPINResponse, error)
	// PINsByOwner lists the PINs owned by an address.
	PINsByOwner(context.Context, *QueryPINsByOwnerRequest) (*QueryPINsByOwnerResponse, error)
	// PINs lists all registered PINs.
	PINs(context.Context, *QueryPINsRequest) (*QueryPINsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) PIN(context.Context, *QueryPINRequest) (*QueryPINResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PIN not implemented")
}
func (UnimplementedQueryServer) PINsByOwner(context.Context, *QueryPINsByOwnerRequest) (*QueryPINsByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PINsByOwner not implemented")
}
func (UnimplementedQueryServer) PINs(context.Context, *QueryPINsRequest) (*QueryPINsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PINs not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PIN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPINRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PIN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PIN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PIN(ctx, req.(*QueryPINRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PINsByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPINsByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PINsByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PINsByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PINsByOwner(ctx, req.(*QueryPINsByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PINs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPINsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PINs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PINs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PINs(ctx, req.(*QueryPINsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pinchain.pin.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "PIN",
			Handler:    _Query_PIN_Handler,
		},
		{
			MethodName: "PINsByOwner",
			Handler:    _Query_PINsByOwner_Handler,
		},
		{
			MethodName: "PINs",
			Handler:    _Query_PINs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pinchain/pin/query.proto",
}
