// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pinchain/pin/pin.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PINStatus is the lifecycle status of a PIN record.
type PINStatus int32

const (
	// PIN_STATUS_UNSPECIFIED is an invalid/unset status.
	PIN_STATUS_UNSPECIFIED PINStatus = 0
	// PIN_STATUS_ACTIVE means the PIN resolves to its owner and can receive funds.
	PIN_STATUS_ACTIVE PINStatus = 1
	// PIN_STATUS_REVOKED means the PIN no longer resolves for transfers.
	PIN_STATUS_REVOKED PINStatus = 2
)

var PINStatus_name = map[int32]string{
	0: "PIN_STATUS_UNSPECIFIED",
	1: "PIN_STATUS_ACTIVE",
	2: "PIN_STATUS_REVOKED",
}

var PINStatus_value = map[string]int32{
	"PIN_STATUS_UNSPECIFIED": 0,
	"PIN_STATUS_ACTIVE":      1,
	"PIN_STATUS_REVOKED":     2,
}

func (x PINStatus) String() string {
	return proto.EnumName(PINStatus_name, int32(x))
}

func (PINStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1558c7be22135ad4, []int{0}
}

// PINRecord is the on-chain, consensus-critical mapping of a human readable PIN
// to the account address that owns it. The PIN is an identifier only: it is
// never a credential and grants no signing authority.
type PINRecord struct {
	// pin is the canonical (uppercase, XXX-XXXX) PIN.
	Pin string `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	// owner is the bech32 account address the PIN resolves to.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// creation_height is the block height at which the PIN was registered.
	CreationHeight int64 `protobuf:"varint,3,opt,name=creation_height,json=creationHeight,proto3" json:"creation_height,omitempty"`
	// status is the PIN lifecycle status.
	Status PINStatus `protobuf:"varint,4,opt,name=status,proto3,enum=pinchain.pin.PINStatus" json:"status,omitempty"`
}

func (m *PINRecord) Reset()         { *m = PINRecord{} }
func (m *PINRecord) String() string { return proto.CompactTextString(m) }
func (*PINRecord) ProtoMessage()    {}
func (*PINRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_1558c7be22135ad4, []int{0}
}
func (m *PINRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PINRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PINRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PINRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PINRecord.Merge(m, src)
}
func (m *PINRecord) XXX_Size() int {
	return m.Size()
}
func (m *PINRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PINRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PINRecord proto.InternalMessageInfo

func (m *PINRecord) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

func (m *PINRecord) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *PINRecord) GetCreationHeight() int64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *PINRecord) GetStatus() PINStatus {
	if m != nil {
		return m.Status
	}
	return PIN_STATUS_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("pinchain.pin.PINStatus", PINStatus_name, PINStatus_value)
	proto.RegisterType((*PINRecord)(nil), "pinchain.pin.PINRecord")
}

func init() { proto.RegisterFile("pinchain/pin/pin.proto", fileDescriptor_1558c7be22135ad4) }

var fileDescriptor_1558c7be22135ad4 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xc8, 0xcc, 0x4b,
	0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x2f, 0x80, 0x60, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x1e,
	0x98, 0xb8, 0x5e, 0x41, 0x66, 0x9e, 0x94, 0x60, 0x62, 0x6e, 0x66, 0x5e, 0xbe, 0x3e, 0x98, 0x84,
	0x28, 0x90, 0x92, 0x4c, 0xce, 0x2f, 0xce, 0xcd, 0x2f, 0x8e, 0x07, 0xf3, 0xf4, 0x21, 0x1c, 0xa8,
	0x94, 0x48, 0x7a, 0x7e, 0x7a, 0x3e, 0x44, 0x1c, 0xc4, 0x82, 0x88, 0x2a, 0x9d, 0x62, 0xe4, 0xe2,
	0x0c, 0xf0, 0xf4, 0x0b, 0x4a, 0x4d, 0xce, 0x2f, 0x4a, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0xc8, 0xcc,
	0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0xf4, 0xb8, 0x58, 0xf3, 0xcb, 0xf3,
	0x52, 0x8b, 0x24, 0x98, 0x40, 0x62, 0x4e, 0x12, 0x97, 0xb6, 0xe8, 0x8a, 0x40, 0x8d, 0x75, 0x4c,
	0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x0e, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x0f, 0x82, 0x28, 0x13, 0x52,
	0xe7, 0xe2, 0x4f, 0x2e, 0x4a, 0x4d, 0x2c, 0xc9, 0xcc, 0xcf, 0x8b, 0xcf, 0x48, 0xcd, 0x4c, 0xcf,
	0x28, 0x91, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0e, 0xe2, 0x83, 0x09, 0x7b, 0x80, 0x45, 0x85, 0xf4,
	0xb9, 0xd8, 0x8a, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x25, 0x58, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0xc4,
	0xf5, 0x90, 0xfd, 0xa6, 0x17, 0xe0, 0xe9, 0x17, 0x0c, 0x96, 0x0e, 0x82, 0x2a, 0xb3, 0x52, 0x7c,
	0xb1, 0x40, 0x9e, 0xb1, 0xeb, 0xf9, 0x06, 0x2d, 0x09, 0x78, 0xe0, 0x54, 0x80, 0x83, 0x07, 0xee,
	0x7c, 0xad, 0x18, 0xb0, 0x5f, 0x20, 0xfa, 0x84, 0xa4, 0xb8, 0xc4, 0x02, 0x3c, 0xfd, 0xe2, 0x83,
	0x43, 0x1c, 0x43, 0x42, 0x83, 0xe3, 0x43, 0xfd, 0x82, 0x03, 0x5c, 0x9d, 0x3d, 0xdd, 0x3c, 0x5d,
	0x5d, 0x04, 0x18, 0x84, 0x44, 0xb9, 0x04, 0x91, 0xe4, 0x1c, 0x9d, 0x43, 0x3c, 0xc3, 0x5c, 0x05,
	0x18, 0x85, 0xc4, 0xb8, 0x84, 0x90, 0x84, 0x83, 0x5c, 0xc3, 0xfc, 0xbd, 0x5d, 0x5d, 0x04, 0x98,
	0xa4, 0x58, 0x3a, 0x16, 0xcb, 0x31, 0x38, 0x39, 0x9d, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c,
	0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1,
	0x1c, 0x43, 0x94, 0x46, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0x72,
	0xcc, 0x21, 0xbb, 0xb2, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0x1c, 0xea, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x79, 0x02, 0x2d, 0xf6, 0xe1, 0x01, 0x00, 0x00,
}

func (this *PINRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PINRecord)
	if !ok {
		that2, ok := that.(PINRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Pin != that1.Pin {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.CreationHeight != that1.CreationHeight {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	return true
}
func (m *PINRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PINRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PINRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintPin(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if m.CreationHeight != 0 {
		i = encodeVarintPin(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintPin(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Pin) > 0 {
		i -= len(m.Pin)
		copy(dAtA[i:], m.Pin)
		i = encodeVarintPin(dAtA, i, uint64(len(m.Pin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPin(dAtA []byte, offset int, v uint64) int {
	offset -= sovPin(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PINRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pin)
	if l > 0 {
		n += 1 + l + sovPin(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovPin(uint64(l))
	}
	if m.CreationHeight != 0 {
		n += 1 + sovPin(uint64(m.CreationHeight))
	}
	if m.Status != 0 {
		n += 1 + sovPin(uint64(m.Status))
	}
	return n
}

func sovPin(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPin(x uint64) (n int) {
	return sovPin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PINRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PINRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PINRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PINStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPin
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPin
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPin
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPin        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPin          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPin = fmt.Errorf("proto: unexpected end of group")
)
